-- Temporary fixtures only; run inside a transaction ending in ROLLBACK.
do $$
declare ua uuid:=gen_random_uuid();ub uuid:=gen_random_uuid();cls uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();g1 uuid;g2 uuid;t uuid;offer uuid;
begin
 insert into auth.users(id) values(ua),(ub);
 insert into public.classes(id,slug,title) values(cls,'animal-test-'||cls,'Animal test');
 insert into public.oases(id,class_id,student_number,invite_hash,owner_auth_uid,oasis_name,stars) values(a,cls,1,a::text,ua,'Animals A',200),(b,cls,2,b::text,ub,'Animals B',200);
 perform set_config('request.jwt.claim.sub',ua::text,true);
 set constraints maintain_animal_home immediate;
 set constraints expand_oasis_land immediate;
 perform public.purchase_item('goat',0);
 select id into g1 from public.items where oasis_id=a and slot_index=0;
 perform public.purchase_item('goat',0);
 select id into g2 from public.items where oasis_id=a and id<>g1;
 assert (select count(*)=2 from public.items where oasis_id=a),'two animals in one home';
 assert (select animal_home_slot=0 and stars=184 from public.oases where id=a),'home and star cost';
 perform public.set_animal_companion(g1);perform public.set_animal_companion(g2);
 assert (select companion_item_id=g2 from public.oases where id=a),'one companion';
 perform public.set_animal_home(5);
 perform public.purchase_item('palms',3);
 select id into t from public.items where oasis_id=a and slot_index=3;
 begin perform public.set_animal_companion(t);raise exception 'TEST FAILED nonanimal';exception when others then if sqlerrm not like 'Choose an animal you own%' then raise;end if;end;
 begin perform public.set_animal_home(3);raise exception 'TEST FAILED building';exception when others then if sqlerrm not like 'Choose a clear spot%' then raise;end if;end;
 begin perform public.set_animal_home(8);raise exception 'TEST FAILED locked';exception when others then if sqlerrm not like 'That land has not opened%' then raise;end if;end;
 perform public.purchase_item('palms',0);
 assert exists(select 1 from public.items where id=g1 and slot_index=2),'visually vacated slot reused';
 assert (select count(*)=4 from public.items where oasis_id=a),'no animal lost';
 offer:=public.create_trade_offer(b,g2,null,3);
 perform public.move_item(t,1);
 assert exists(select 1 from public.items where id=g2 and slot_index=3),'moving building swaps animal inventory';
 assert exists(select 1 from public.trade_offers where id=offer and status='pending'),'move preserves offer';
 assert (select companion_item_id=g2 from public.oases where id=a),'move preserves pet';
 perform public.set_animal_home(3);
 begin perform public.purchase_item('tent',3);raise exception 'TEST FAILED home overwritten';exception when others then if sqlerrm not like 'Move the animal home%' then raise;end if;end;
 perform public.purchase_item('goat',3);perform public.purchase_item('palms',6);
 assert (select land_level=2 from public.oases where id=a),'grouped animals expand land';
 perform public.set_animal_home(15);
 perform set_config('request.jwt.claim.sub',ub::text,true);
 begin perform public.set_animal_companion(g2);raise exception 'TEST FAILED ownership';exception when others then if sqlerrm not like 'Choose an animal you own%' then raise;end if;end;
 assert public.resolve_trade_offer(offer,true)='accepted','companion trade';
 assert (select companion_item_id is null and animal_home_slot=15 from public.oases where id=a),'former pet cleared';
 assert (select animal_home_slot=0 from public.oases where id=b),'received animal starts home';
 perform public.set_animal_companion(g2);
 perform public.sell_item(g2);
 assert (select animal_home_slot is null and companion_item_id is null from public.oases where id=b),'last animal sale clears home';
 assert not has_function_privilege('anon','public.set_animal_companion(uuid)','EXECUTE'),'anon denied';
 assert not has_function_privilege('authenticated','private.maintain_animal_home()','EXECUTE'),'trigger internal only';
 assert not has_table_privilege('authenticated','public.oases','UPDATE'),'direct updates denied';
end $$;
select 'PASS: grouped purchases, home/companion ownership, locked land, slot reuse, pending trades, pet transfer and sale cleanup' as result;
