-- Run inside BEGIN / ROLLBACK; only temporary test players are changed.
do $$
declare ua uuid:=gen_random_uuid();ub uuid:=gen_random_uuid();cls uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();hen uuid;hen2 uuid;goat uuid;coop uuid;pen uuid;offer uuid;balance integer;
begin
 insert into auth.users(id) values(ua),(ub);
 insert into public.classes(id,slug,title) values(cls,'hen-test-'||cls,'Chicken test');
 insert into public.oases(id,class_id,student_number,invite_hash,owner_auth_uid,oasis_name,stars,land_level) values(a,cls,1,a::text,ua,'Hens A',200,4),(b,cls,2,b::text,ub,'Hens B',200,4);
 perform set_config('request.jwt.claim.sub',ua::text,true);
 set constraints maintain_animal_home immediate;
 set constraints expand_oasis_land immediate;
 perform public.purchase_item('goat',0);select id into goat from public.items where oasis_id=a and item_type='goat';
 perform public.purchase_item('chicken',0);select id into hen from public.items where oasis_id=a and item_type='chicken';
 perform public.purchase_item('chicken',0);select id into hen2 from public.items where oasis_id=a and item_type='chicken' and id<>hen;
 assert (select stars=180 from public.oases where id=a),'chicken cost';
 perform public.purchase_item('pen',8);select id into pen from public.items where oasis_id=a and item_type='pen';
 perform public.purchase_item('coop',12);select id into coop from public.items where oasis_id=a and item_type='coop';
 begin perform public.set_pen_animals(coop,array[goat]);raise exception 'TEST FAILED goat in coop';exception when others then if sqlerrm not like 'Choose the matching animal%' then raise;end if;end;
 begin perform public.set_pen_animals(pen,array[hen]);raise exception 'TEST FAILED hen in goat pen';exception when others then if sqlerrm not like 'Choose the matching animal%' then raise;end if;end;
 perform public.set_pen_animals(pen,array[goat]);perform public.set_pen_animals(coop,array[hen,hen2]);
 perform public.set_animal_companion(goat);perform public.set_animal_companion(hen);
 assert (select companion_item_id=hen from public.oases where id=a),'switch between species';
 select stars into balance from public.oases where id=a;
 assert public.collect_eggs()=2,'first eggs';
 assert (select eggs=2 and stars=balance from public.oases where id=a),'egg basket separate from stars';
 begin perform public.collect_eggs();raise exception 'TEST FAILED duplicate eggs';exception when others then if sqlerrm not like 'Your chickens are still laying%' then raise;end if;end;
 perform public.set_pen_animals(coop,'{}');perform public.set_pen_animals(coop,array[hen,hen2]);
 begin perform public.collect_eggs();raise exception 'TEST FAILED reassign bypass';exception when others then if sqlerrm not like 'Your chickens are still laying%' then raise;end if;end;
 update public.oases set eggs_collected_at=now()-interval '24 hours' where id=a;
 assert public.collect_eggs()=2,'next collection';
 assert (select eggs=4 from public.oases where id=a),'eggs accumulate';
 offer:=public.create_trade_offer(b,hen,'goat',null);
 perform set_config('request.jwt.claim.sub',ub::text,true);
 perform public.purchase_item('goat',0);select id into goat from public.items where oasis_id=b;
 assert public.resolve_trade_offer(offer,true,goat)='accepted','chicken barter';
 assert (select pen_item_id is null and oasis_id=b from public.items where id=hen),'hen leaves former coop on transfer';
 assert (select companion_item_id is null from public.oases where id=a),'old companion cleared';
 assert public.sell_item(hen)=3,'chicken refund';
 perform set_config('request.jwt.claim.sub',ua::text,true);
 assert public.sell_item(coop)=6,'coop refund';
 assert exists(select 1 from public.items where id=hen2 and pen_item_id is null),'coop sale preserves hen';
 assert (select eggs=4 from public.oases where id=a),'coop sale preserves basket';
 begin perform public.collect_eggs();raise exception 'TEST FAILED unhoused eggs';exception when others then if sqlerrm not like 'Give your chickens a coop%' then raise;end if;end;
 assert not has_function_privilege('anon','public.collect_eggs()','EXECUTE'),'anon cannot collect';
 perform public.purchase_item('coop',12);select id into coop from public.items where oasis_id=a and item_type='coop';
 perform public.set_pen_animals(coop,array[hen2]);
 update public.oases set eggs_collected_at=now()-interval '24 hours' where id=a;
end $$;
set local role authenticated;
select public.collect_eggs() as authenticated_egg_collection;
reset role;
select 'PASS: chickens, coop species, cross-species pet choice, daily eggs, no clock reset via reassignment, separate stars, trade and refunds' as result;
