-- Roll back all fixtures after running this script.
do $$
declare ua uuid:=gen_random_uuid();ub uuid:=gen_random_uuid();cls uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();animals uuid[];p uuid;p2 uuid;offer uuid;stars_before integer;
begin
 insert into auth.users(id) values(ua),(ub);
 insert into public.classes(id,slug,title) values(cls,'pen-test-'||cls,'Pen test');
 insert into public.oases(id,class_id,student_number,invite_hash,owner_auth_uid,oasis_name,stars,land_level) values(a,cls,1,a::text,ua,'Pens A',500,4),(b,cls,2,b::text,ub,'Pens B',500,4);
 perform set_config('request.jwt.claim.sub',ua::text,true);
 set constraints maintain_animal_home immediate;
 set constraints expand_oasis_land immediate;
 for i in 1..7 loop perform public.purchase_item('goat',0);end loop;
 select array_agg(id order by id) into animals from public.items where oasis_id=a;
 perform public.set_animal_companion(animals[1]);
 begin perform public.purchase_item('pen',0);raise exception 'TEST FAILED wet pen';exception when others then if sqlerrm not like 'Choose a roomy, dry spot%' then raise;end if;end;
 select stars into stars_before from public.oases where id=a;
 perform public.purchase_item('pen',8);select id into p from public.items where oasis_id=a and item_type='pen';
 assert (select stars=stars_before-12 from public.oases where id=a),'pen price';
 perform public.set_pen_animals(p,animals[1:6]);
 assert (select count(*)=6 from public.items where pen_item_id=p),'six residents';
 assert (select companion_item_id=animals[1] from public.oases where id=a),'assigned pet retained';
 begin perform public.set_pen_animals(p,animals);raise exception 'TEST FAILED overcapacity';exception when others then if sqlerrm not like 'This pen has room for six%' then raise;end if;end;
 perform public.purchase_item('pen',3);
 begin perform public.purchase_item('tent',4);raise exception 'TEST FAILED overlapping';exception when others then if sqlerrm not like 'Leave room around%' then raise;end if;end;
 perform public.sell_item((select id from public.items where oasis_id=a and item_type='pen' and slot_index=3));
 assert (select count(*)=7 from public.items where oasis_id=a and item_type='goat'),'failed purchases preserved animals';
 perform public.move_item(p,21);
 assert (select slot_index=21 from public.items where id=p),'pen move';
 assert (select count(*)=6 from public.items where pen_item_id=p),'pen move keeps residents';
 perform public.purchase_item('pen',8);select id into p2 from public.items where oasis_id=a and item_type='pen' and id<>p;
 perform public.set_pen_animals(p2,animals[6:7]);
 assert (select count(*)=5 from public.items where pen_item_id=p),'move animal between pens';
 assert (select count(*)=2 from public.items where pen_item_id=p2),'second pen residents';
 begin perform public.create_trade_offer(b,p,null,1);raise exception 'TEST FAILED pen trade';exception when others then if sqlerrm not like 'Pens stay on your Oasis%' then raise;end if;end;
 offer:=public.create_trade_offer(b,animals[1],null,3);
 perform set_config('request.jwt.claim.sub',ub::text,true);
 begin perform public.set_pen_animals(p,animals[1:2]);raise exception 'TEST FAILED other pen';exception when others then if sqlerrm not like 'Choose a pen you own%' then raise;end if;end;
 perform public.purchase_item('pen',8);select id into p2 from public.items where oasis_id=b and item_type='pen';
 begin perform public.set_pen_animals(p2,animals[1:2]);raise exception 'TEST FAILED other animals';exception when others then if sqlerrm not like 'Choose animals you own%' then raise;end if;end;
 assert public.resolve_trade_offer(offer,true)='accepted','penned animal traded';
 assert (select pen_item_id is null and oasis_id=b from public.items where id=animals[1]),'received animal leaves old pen';
 assert (select companion_item_id is null from public.oases where id=a),'former pet cleared';
 perform public.set_pen_animals(p2,animals[1:1]);
 assert public.sell_item(p2)=6,'pen refund';
 assert (select pen_item_id is null from public.items where id=animals[1]),'pen sale frees resident';
 assert exists(select 1 from public.items where id=animals[1] and oasis_id=b),'pen sale preserves goat';
 assert not has_function_privilege('anon','public.set_pen_animals(uuid,uuid[])','EXECUTE'),'anon denied';
 assert not has_function_privilege('authenticated','private.check_pen_change()','EXECUTE'),'internal trigger';
 perform set_config('request.jwt.claim.sub',ua::text,true);
 perform set_config('pen.test.pen',p::text,true);
end $$;
set local role authenticated;
select public.set_pen_animals(current_setting('pen.test.pen')::uuid,'{}'::uuid[]);
reset role;
select 'PASS: pen costs, six animal capacity, ownership, pond and overlap rejection, move, multiple pens, transfer, pet choice and sale cleanup' as result;
