import {drawBasket} from '../public/style-preview/basket.js';
import {plots,heightForLevel,buildSlots,project,pathTo,isWater,shorePoints,plotOutline,pointInPlot,buildingPosition} from './illustrated-world.js';
import {GoatLife} from '../public/style-preview/goat-life.js';
import {recolor,cleanColors} from '../public/style-preview/customization.js';
import {isAnimal,animalHomeSlot,ownedAnimals} from './animals.js';
import {isPen,animalPen,penResidents,penLocationAvailable,buildingClearOfPens} from './pens.js';
const W=1536,assets={},colored=new Map(),bounds={};
const art=name=>`${import.meta.env.BASE_URL}style-preview/art/${name}.webp?v=4`;
export async function loadIllustratedArt(){if(assets.terrain)return;await Promise.all(['terrain','objects','avatar','avatar-boy-v2','chicken-yard-v2','expansion-v1'].map(async name=>{const image=new Image();image.src=art(name);await image.decode();assets[name]=image;}));for(const[name,cols,rows]of [['objects',3,2],['chicken-yard-v2',1,1]])bounds[name]=crop(assets[name],cols,rows);}
function crop(image,cols,rows){const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data,sw=c.width/cols,sh=c.height/rows,result=[];for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){let x1=sw,y1=sh,x2=0,y2=0;for(let y=0;y<sh;y++)for(let x=0;x<sw;x++)if(data[((j*sh+y)*c.width+i*sw+x)*4+3]>24){x1=Math.min(x1,x);y1=Math.min(y1,y);x2=Math.max(x2,x);y2=Math.max(y2,y);}result.push({sx:i*sw+x1,sy:j*sh+y1,w:x2-x1+1,h:y2-y1+1});}return result;}
export function avatarColors(avatar){return cleanColors(avatar.colors?.[avatar.style==='boy'?'boy':'girl']||{skin:avatar.skin,hair:avatar.hair,outfit:avatar.clothes});}
function avatarImage(avatar){const style=avatar.style==='boy'?'boy':'girl',colors=avatarColors(avatar),key=style+JSON.stringify(colors);if(!colored.has(key)){if(colored.size>16)colored.clear();colored.set(key,recolor(style==='boy'?assets['avatar-boy-v2']:assets.avatar,style,colors));}return colored.get(key);}
export function drawAvatarPreview(canvas,avatar){let ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(avatarImage(avatar),0,512,256,512,0,0,canvas.width,canvas.height);}
export function mountIllustratedGame(id,getOasis,onSpot,onItem,onWalk,onAvatar,getIntent){
 const root=document.getElementById(id),canvas=document.createElement('canvas');canvas.tabIndex=0;canvas.setAttribute('aria-label','Your Oasis. Tap a path to walk or a glowing plot to build. Drag to explore.');root.append(canvas);let ctx=canvas.getContext('2d');let cw=1,ch=1,scale=1,H=1024,last=0,time=0,route=[],walking=false,face=1,frame=0,active=true;const player={x:690,y:640},camera={x:768,y:512,zoom:1,follow:false},lives=new Map(),pointers=new Map();let press=null,pinch=null,hitboxes=[],slots=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function view(){H=heightForLevel(getOasis().land_level||1);scale=Math.min(cw/W,ch/1024)*camera.zoom;camera.x=cw/scale>=W?W/2:Math.max(cw/(2*scale),Math.min(W-cw/(2*scale),camera.x));camera.y=ch/scale>=H?H/2:Math.max(ch/(2*scale),Math.min(H-ch/(2*scale),camera.y));}
 function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);cw=r.width;ch=r.height;canvas.width=cw*d;canvas.height=ch*d;ctx.setTransform(d,0,0,d,0,0);view();}canvas.style.width='100%';canvas.style.height='100%';new ResizeObserver(resize).observe(canvas);
 function sprite(name,cell,p,w,flip=false,bob=0){const b=bounds[name][cell],h=w*b.h/b.w;ctx.save();ctx.translate(p.x,p.y+bob);if(flip)ctx.scale(-1,1);ctx.drawImage(assets[name],b.sx,b.sy,b.w,b.h,-w/2,-h,w,h);ctx.restore();return{left:p.x-w/2,right:p.x+w/2,top:p.y-h,bottom:p.y};}
 function homeFor(item,oasis){const pen=animalPen(oasis,item),group=pen?penResidents(oasis,pen):ownedAnimals(oasis).filter(a=>!animalPen(oasis,a)),index=group.findIndex(a=>a.id===item.id),p=plots[pen?.slot_index??animalHomeSlot(oasis)??item.slot_index];const col=index%3,row=Math.floor(index/3);return{home:{x:p.x-65+col*65,y:p.y+5+row*28},door:{x:p.door[0],y:p.door[1]}};}
 function animalFrame(oasis,dt){const animals=[];for(const item of ownedAnimals(oasis)){const{home,door}=homeFor(item,oasis),pet=item.id===oasis.companion_item_id;let life=lives.get(item.id);if(!life){life=new GoatLife(false,{...home},{project,pathTo});life.homeKey=`${home.x},${home.y}`;lives.set(item.id,life);}life.update(dt,time,player,home,door,pet);animals.push({item,x:life.x,y:life.y,life});}for(const id of lives.keys())if(!oasis.items.some(i=>i.id===id))lives.delete(id);return animals;}
 function drawLand(){ctx.fillStyle='#dfb778';ctx.fillRect(0,0,W,H);for(let y=900;y<H;y+=900)ctx.drawImage(assets['expansion-v1'],0,0,1536,900,0,y,1536,900);// Fade the old edge into the expansion instead of exposing a hard image boundary.
 const terrain=document.createElement('canvas');terrain.width=W;terrain.height=1024;const t=terrain.getContext('2d');t.drawImage(assets.terrain,0,0,W,1024);
 if(H>1024){t.globalCompositeOperation='destination-out';const fade=t.createLinearGradient(0,900,0,1024);fade.addColorStop(0,'rgba(0,0,0,0)');fade.addColorStop(1,'rgba(0,0,0,1)');t.fillStyle=fade;t.fillRect(0,900,W,124);}ctx.drawImage(terrain,0,0);}
 function outlinePlot(slot){const polygon=plotOutline(slot);ctx.beginPath();polygon.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}
 let background=null;function land(){if(!background||background.height!==H){background=document.createElement('canvas');background.width=W;background.height=H;const main=ctx;ctx=background.getContext('2d');drawLand();ctx=main;}ctx.drawImage(background,0,0);}
 function paint(dt){const oasis=getOasis();view();ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#d8b37d';ctx.fillRect(0,0,cw,ch);ctx.save();ctx.translate(cw/2-camera.x*scale,ch/2-camera.y*scale);ctx.scale(scale,scale);land();
 if(!reduced)for(const[x,y,offset]of [[785,414,0],[916,455,.4],[800,510,.7]]){const phase=(time/3200+offset)%1;ctx.strokeStyle=`rgba(237,255,249,${Math.sin(phase*Math.PI)*.42})`;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y,12+phase*35,4+phase*10,0,0,Math.PI*2);ctx.stroke();}
 // The lot outline, placement target and building anchor share one coordinate model.
 for(let i=0;i<Math.min(32,(oasis.land_level||1)*8);i++)if(plots[i].expansion){outlinePlot(i);ctx.strokeStyle='#b3894b70';ctx.lineWidth=3;ctx.stroke();}
 slots=buildSlots(oasis,getIntent(),{isPen,isAnimal,animalHomeSlot,penLocationAvailable,buildingClearOfPens});
 for(const p of slots){outlinePlot(p.index);ctx.fillStyle='#fff3c024';ctx.fill();ctx.strokeStyle='#fff3c0dd';ctx.setLineDash([8,7]);ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#4d432a';ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillText(p.index+1,p.x,p.y+6);}
 const animals=animalFrame(oasis,dt),drawables=oasis.items.filter(i=>!isAnimal(i.item_type)).map(item=>{const p=plots[item.slot_index],position=buildingPosition(item.slot_index,item.item_type);return{item,...position,depth:item.item_type==='coop'?p.y-45:position.y};});drawables.push(...animals,{player:true,...player});drawables.sort((a,b)=>(a.depth??a.y)-(b.depth??b.y));hitboxes=[];
 for(const d of drawables){if(d.player){ctx.save();ctx.translate(d.x,d.y);if(face<0)ctx.scale(-1,1);const bob=walking&&!reduced?-Math.abs(Math.sin(time/110))*1.3:0;ctx.drawImage(avatarImage(oasis.avatar),(frame%6)*256,Math.floor(frame/6)*512,256,512,-34,-125+bob,68,136);if(oasis.eggs>0)drawBasket(ctx);ctx.restore();}else{const type=d.item.item_type,animal=isAnimal(type);ctx.fillStyle='#67482230';ctx.beginPath();ctx.ellipse(d.x,d.y-(type==='tent'?25:0),animal?16:65,animal?4:14,0,0,Math.PI*2);ctx.fill();const name=type==='coop'?'chicken-yard-v2':'objects',cell={tent:0,pen:1,coop:0,goat:3,chicken:4,palms:5}[type],w=animal?(type==='goat'?64:48):type==='palms'?160:260;const b=sprite(name,cell,d,w,d.life?.face>0,d.life?.moving&&!reduced?-Math.abs(Math.sin(time/150))* (type==='goat'?7:2):0);hitboxes.push({item:d.item,...b});}}
 ctx.restore();canvas.dataset.state=JSON.stringify({player,walking,avatarStyle:oasis.avatar.style||'girl',eggs:oasis.eggs||0,basket:oasis.eggs>0,landLevel:oasis.land_level||1,height:H,zoom:camera.zoom,camera:{x:camera.x,y:camera.y},scale,buildSlots:slots.map(p=>p.index),animals:animals.map(a=>({id:a.item.id,type:a.item.item_type,x:a.x,y:a.y,mode:a.life.mode,moving:a.life.moving})),items:oasis.items.map(i=>({id:i.id,type:i.item_type,slot:i.slot_index}))});canvas.dataset.animals=JSON.stringify(animals.map(a=>({id:a.item.id,x:a.x/W,y:a.y/1024,mode:a.life.mode})));onAvatar({x:.5+(player.x-camera.x)*scale/cw,y:.5+(player.y-camera.y)*scale/ch,height:136*scale/ch,worldX:player.x/W,worldY:player.y/1024,zoom:camera.zoom,walking,facingLeft:face<0});}
 function tick(now){if(!active)return;const dt=Math.min((now-last)/1000,.05);last=now;time=now;walking=route.length>0;if(walking){const p=route[0],dx=p.x-player.x,dy=p.y-player.y,d=Math.hypot(dx,dy),step=170*dt;if(Math.abs(dx)>1)face=dx>0?1:-1;if(d<=step){Object.assign(player,p);route.shift();}else{player.x+=dx/d*step;player.y+=dy/d*step;}}frame=walking&&!reduced?Math.floor(time/125)%6:6+Math.floor(time/1400)%3;if(camera.follow){camera.x+=(player.x-camera.x)*.09;camera.y+=(player.y-camera.y)*.09;}paint(dt);requestAnimationFrame(tick);}
 function world(p){return{x:(p.x-cw/2)/scale+camera.x,y:(p.y-ch/2)/scale+camera.y};}function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.x,y:e.clientY-r.y};}
 function tap(p){if(document.querySelector('.scrim'))return;const item=[...hitboxes].reverse().find(b=>p.x>=b.left&&p.x<=b.right&&p.y>=b.top&&p.y<=b.bottom);if(item)return onItem(item.item);const slot=slots.find(b=>pointInPlot(p,b.index));if(slot)return onSpot(slot.index);onWalk(p.x/W,p.y/1024);}
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);const p=point(e);pointers.set(e.pointerId,p);if(pointers.size===1)press={...p,x0:camera.x,y0:camera.y,dragged:false};if(pointers.size===2){const[a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:camera.zoom};press.dragged=true;}};
 canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const p=point(e);pointers.set(e.pointerId,p);if(pointers.size===2&&pinch){const[a,b]=[...pointers.values()];camera.zoom=Math.max(1024/H,Math.min(4,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance));camera.follow=false;}else if(press&&Math.hypot(p.x-press.x,p.y-press.y)>8){press.dragged=true;camera.follow=false;camera.x=press.x0-(p.x-press.x)/scale;camera.y=press.y0-(p.y-press.y)/scale;}};
 canvas.onpointerup=e=>{const isTap=pointers.size===1&&press&&!press.dragged;pointers.delete(e.pointerId);if(isTap)tap(world(point(e)));if(!pointers.size)press=pinch=null;};canvas.onpointercancel=()=>{pointers.clear();press=pinch=null;};canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(1024/H,Math.min(4,camera.zoom*(e.deltaY>0?.9:1.1)));camera.follow=false;},{passive:false});
 resize();requestAnimationFrame(tick);return{refresh(){H=heightForLevel(getOasis().land_level||1);},zoom(direction){camera.zoom=Math.max(1024/H,Math.min(4,camera.zoom*(direction>0?1.3:1/1.3)));},overview(){H=heightForLevel(getOasis().land_level||1);camera.zoom=1024/H;camera.x=W/2;camera.y=H/2;camera.follow=false;},follow(){camera.zoom=2;camera.follow=true;camera.x=player.x;camera.y=player.y;},walkTo(x,y){const p={x:x*W,y:y*1024};if(p.x<0||p.x>W||p.y<0||p.y>H||isWater(p)||project(p).distance>120)return false;route=pathTo(player,p);camera.follow=true;return true;},visitWaterfall(){route=pathTo(player,shorePoints.waterfall);camera.follow=true;},destroy(){active=false;canvas.remove();}};
}

export function drawItemPreview(canvas,type){const ctx=canvas.getContext('2d'),name=type==='coop'?'chicken-yard-v2':'objects',cell={tent:0,pen:1,coop:0,goat:3,chicken:4,palms:5}[type];if(cell===undefined)return;const b=bounds[name][cell],scale=Math.min(canvas.width/b.w,canvas.height/b.h);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(assets[name],b.sx,b.sy,b.w,b.h,(canvas.width-b.w*scale)/2,(canvas.height-b.h*scale)/2,b.w*scale,b.h*scale);}
